SELECT 
first_name,last_name,age,
case
	when age<=30 then 'young'
    when age between 31 and 50 then 'midage'
    when age>=50 then 'old'
end as agelabel
FROM EMPLOYEE_DEMOGRAPHICS;


select * from employee_salary;

SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME,SALARY,
CASE
	WHEN DEPARTMENT_NAME='FINANCE' THEN (SALARY*0.1)
	WHEN SALARY<50000 THEN (SALARY*0.05)
    WHEN SALARY>50000 THEN (SALARY*0.07)
END AS BONUS
FROM EMPLOYEE_SALARY JOIN PARKS_DEPARTMENTS ON EMPLOYEE_SALARY.DEPT_ID=PARKS_DEPARTMENTS.DEPARTMENT_ID;

