-- cte 

-- cte was simila to the subsquery but you can have the named expressions
 
WITH CTE_EXAMPLE AS (
select gender,avg(salary) AS AVERAGE,MIN(SALARY),MAX(SALARY) from employee_demographics dem
join employee_salary sal on dem.employee_id=sal.employee_id
group by gender)

-- WE CAN ONLY USE THE CTE IMMEDIATELY AFTER I CREATE IT
SELECT * FROM CTE_EXAMPLE;


-- WE CANNOT SAVE THE CTE AND WE CANNOT REUSE IT AND WE CANNOT SAVE IT ALSO

-- WE CAN EVEN JOIN TWO CTE TABLES


WITH CTEEXAMPLE1 AS
(
	SELECT EMPLOYEE_ID,BIRTH_DATE,GENDER 
    FROM EMPLOYEE_DEMOGRAPHICS
    WHERE BIRTH_DATE>'1985-01-01'
),
CTEEXAMPLE2 AS 
(
	SELECT EMPLOYEE_ID,SALARY 
    FROM EMPLOYEE_SALARY
    WHERE SALARY>50000
)
SELECT * 
FROM CTEEXAMPLE1 JOIN CTEEXAMPLE2 
ON CTEEXAMPLE1.EMPLOYEE_ID=CTEEXAMPLE2.EMPLOYEE_ID;


