SELECT * 
FROM EMPLOYEE_DEMOGRAPHICS 
WHERE (FIRST_NAME='LESLIE' AND AGE=44) OR AGE>44;

# FIRST PERENTHESIS WILL BE EXECUTED IN PARALLEL WITH THE OR CLAUSE;

-- LIKE STATEMENT;
SELECT 
*
FROM EMPLOYEE_DEMOGRAPHICS
WHERE FIRST_NAME LIKE '%ER%';

SELECT 
*
FROM EMPLOYEE_DEMOGRAPHICS
WHERE FIRST_NAME LIKE 'A___%';

# _ REPRESENTS THE CHARECTER WHICH COULD BE ANYTHING

SELECT 
*
FROM EMPLOYEE_DEMOGRAPHICS
WHERE FIRST_NAME LIKE 'A__';

SELECT * 
FROM EMPLOYEE_DEMOGRAPHICS
WHERE BIRTH_DATE LIKE '1985%';