-- WHERE CLAUSE

# WHERE WILL ACT AS THE IF STATEMENT FOR THE SQL COMMANDS
SELECT * FROM EMPLOYEE_DEMOGRAPHICS WHERE FIRST_NAME='Leslie';

# comparisoin operators

SELECT * FROM EMPLOYEE_SALARY WHERE SALARY>=50000;
SELECT * FROM EMPLOYEE_SALARY WHERE SALARY<=50000;

SELECT * FROM employee_demographics WHERE GENDER!='MALE';

# WE CAN ALSO USE THE <> NOT EQUAL IN THE PLACE OF !=;

SELECT * FROM employee_demographics WHERE birth_date>'1985-01-01';

-- LOGICAL OPERATORS WHICH INCLUDE THE AND OR NOT CLAUSES;

SELECT * FROM employee_demographics WHERE BIRTH_DAY>'1985-01-01' AND GENDER='MALE';
SELECT * FROM employee_demographics WHERE BIRTH_DAY>'1985-01-01' OR GENDER='MALE';
SELECT * FROM employee_demographics WHERE BIRTH_DAY>'1985-01-01' OR NOT GENDER='MALE';
SELECT * FROM employee_demographics WHERE BIRTH_DAY>'1985-01-01' AND NOT GENDER='MALE';
 