-- groupby
# when we use the groupby that willl group the same values in a particular column and use the aggregate functions on them
SELECT AGE FROM EMPLOYEE_DEMOGRAPHICS GROUP BY AGE;

# IF NOT PERFORMING ANY AGGRAGE FUNCTION GROUPBY SHOULD MATCH THE SELECT COMMAND

SELECT GENDER,AVG(AGE)
FROM employee_demographics
GROUP BY GENDER;

SELECT OCCUPATION,SALARY FROM EMPLOYEE_SALARY
GROUP BY OCCUPATION,SALARY;

-- OTHER AGGRAGATION FUNCTOINS

SELECT GENDER,MAX(AGE)
FROM EMPLOYEE_DEMOGRAPHICS
GROUP BY GENDER;

SELECT GENDER,MIN(AGE) AS MINIMUMAGE 
FROM EMPLOYEE_DEMOGRAPHICS
GROUP BY GENDER;

SELECT GENDER,MIN(AGE),MAX(AGE),COUNT(*) AS FREQ
FROM employee_demographics
GROUP BY GENDER;

-- ORDER BY
# ORDER BY WAS USED TO ORDER THE TABLE WRT TO A PARTICULAR COLUMN

