-- Limit and Aliasing

SELECT * FROM employee_demographics LIMIT 5;

-- BY LIMIT WE CAN ACTUALLY RETRIVE THE TOP 3 OR TOP  5 CONDIDATES

SELECT * FROM EMPLOYEE_SALARY ORDER BY SALARY DESC LIMIT 3,5;

-- THE ABVE LIMIT 3,5 REPRESENTA THE FIVE ROWS AFTER THE TOP 3 OUTPUT 

-- ALIASING

SELECT GENDER,AVG(AGE) AS AVERAGEAGE FROM employee_demographics GROUP BY GENDER HAVING AVERAGEAGE>40;

-- WE CAN ACTUALLY USE THE ALIAS NAME IN THE HAVING CLAUSE;

--JOINS,-- SUBQUERIES, --WINDOWFUNCTIONS 