DELIMITER $$;
CREATE TRIGGER employee_insert
	AFTER INSERT ON EMLOYEE_SALARY
	FOR EACH ROW
BEGIN 
	INSERT INTO EMPLOYEE_DEMOFRAPHICS(EMPLOYEE_ID,FIRST_NAME,LAST_NAME)
	VALUES (NEW.EMPLOYEE_ID,NEW.FIRST_NAME,NEW.LAST_NAME);
END $$

DELIMITER ;
        
	
