-- outer join 
-- outerjoin consist of the leftjoin and the right join
SELECT * 
FROM employee_demographics AS DEM left JOIN employee_salary AS SAL 
ON DEM.employee_id=SAL.employee_id;
-- LEFT TABLE WILL TAKE ALL ROWS IN LEFT TABLE AND DISPLAY MATCHES WITH RIGHT 
-- OF NOT FOUND SHOWN AS NULL

SELECT * 
FROM employee_demographics AS DEM RIGHT JOIN employee_salary AS SAL 
ON DEM.employee_id=SAL.employee_id;
-- RIGHT JOIN WILL TAKE EVERY THING ON THE RIGHT TABLE AND DISPLAY THE MATCHES WITHT THE LEFT TABLE
-- OF NOT MATCHED OT WILL SHOW NULL


-- SELF JOIN
-- WE WILL JOIN THE SAME TABLE TO SELF

SELECT EMP1.EMPLOYEE_ID AS EMPLOYEEID,EMP1.FIRST_NAME AS EMPLOYEENAME,EMP2.EMPLOYEE_ID AS SANTAID,
EMP2.FIRST_NAME AS SANTANAME 
FROM employee_demographics AS EMP1 JOIN employee_demographics AS EMP2
ON EMP1.EMPLOYEE_ID+1=EMP2.EMPLOYEE_ID;

-- JOIN MULTIPLE TABLES TOGETHER
-- JOINING MORE THAN TWO TABLES


SELECT DEM.EMPLOYEE_ID,DEM.FIRST_NAME,SAL.SALARY,AGE,OCCUPATION 
FROM employee_demographics AS DEM JOIN employee_salary AS SAL 
ON DEM.employee_id=SAL.employee_id;


SELECT * FROM PARKS_DEPARTMENTS;

-- PARKS AND DEPARTMENTS WAS A REFERENCE TABLE DOSENT CHANGE FREQUENTLY 
-- ONLY FOR REFERENCE
-- IT ONLY CONSIST OF THE DEPARTMENT_ID AND CORRESPONDING NAME


SELECT *
FROM employee_demographics AS DEM JOIN EMPLOYEE_SALARY AS SAL ON DEM.EMPLOYEE_ID= SAL.EMPLOYEE_ID
JOIN PARKS_DEPARTMENTS ON PARKS_DEPARTMENTS.DEPARTMENT_ID=SAL.DEPT_ID;
