SELECT * FROM EMPLOYEE_DEMOGRAPHICS;
-- WE CAN SELECT COLUMN WISE ALSO USING THE SELECT STATEMENT;

SELECT employee_id,
FIRST_NAME,
LAST_NAME,
AGE,
(AGE+10)*10 AS UPDATEDNUM
FROM EMPLOYEE_DEMOGRAPHICS; 

# FOLLOWS THE RULES OF PEMDAS
# USED FOR THE NOTETAKING IN THE SQL COMMAND
# PERENTHESEIS
# EMPONENTIAL
# MULTIPLICATION
# DIVISION
# ADDITION
# SUBTRACTION

-- DISTINCT KEYWORD
# DISTINCT KEYWORD WILL GIVE US THE ONLY THE UNIQUE ELEMENTS IN A PARTICULAR COLUMN


SELECT DISTINCT FIRST_NAME FROM EMPLOYEE_DEMOGRAPHICS;
SELECT DISTINCT GENDER FROM EMPLOYEE_DEMOGRAPHICS;

SELECT DISTINCT FIRST_NAME,GENDER FROM EMPLOYEE_DEMOGRAPHICS;

-- SELECT FIRST_NAME,DISTINCT AGE FROM EMPLOYEE_DEMOGRAPHICS;--
# DISTINCT SHOULD BE USED IMMEDIATELY AFTER THE SELECT STATEMNT NOT IN BETWEEN BECAUSE DISTINCT WORKS TO ENTIRE ROW;
 
