-- STRING FUNCTIONS

SELECT FIRST_NAME,LENGTH(FIRST_NAME) 
FROM 
EMPLOYEE_DEMOGRAPHICS
ORDER BY LENGTH(FIRST_NAME);

SELECT FIRST_NAME,UPPER(FIRST_NAME),LOWER(FIRST_NAME)
 FROM 
 EMPLOYEE_DEMOGRAPHICS;
 
 SELECT TRIM('      SKY        ');

-- TRIM WILL WILL CUT THE LEADING AND TRAILING
SELECT LTRIM('       SKY      ');
SELECT RTRIM('      SKY       ');

-- LEFT AND RIGHT TRIM

-- SUBSTRING
SELECT FIRST_NAME,LEFT(FIRST_NAME,4),RIGHT(FIRST_NAME,4)
FROM EMPLOYEE_DEMOGRAPHICS;

SELECT FIRST_NAME,SUBSTRING(FIRST_NAME,1,4) FROM employee_demographics;
SELECT FIRST_NAME,SUBSTRING(FIRST_NAME,2,3) FROM employee_demographics;
SELECT FIRST_NAME,SUBSTRING(FIRST_NAME,1,4),SUBSTRING(BIRTH_DATE,6,2)AS BIRTHMONTH FROM employee_demographics;


SELECT FIRST_NAME,REPLACE(FIRST_NAME,'a','z')
from employee_demographics;


-- LOCATE FRUNCTION
SELECT LOCATE('X','ALEXANDER');

SELECT LOCATE('A',FIRST_NAME),FIRST_NAME FROM EMPLOYEE_DEMOGRAPHICS;
-- o means it is not there


-- concatenation of multiple columns

select first_name,last_name,CONCAT(FIRST_NAME," ",LAST_NAME)
FROM EMPLOYEE_DEMOGRAPHICS;