-- subquery

SELECT * FROM EMPLOYEE_DEMOGRAPHICS;

-- WE HAVE TO GET THE EMPLOYEE ID WHOSE DEPTID=1;
SELECT EMPLOYEE_ID FROM EMPLOYEE_SALARY WHERE DEPT_ID=1;

SELECT * FROM
employee_demographics
WHERE EMPLOYEE_ID IN (SELECT employee_id FROM EMPLOYEE_SALARY WHERE DEPT_ID=1);

-- WE CANNOT RETURN TWO COLUMNS IN SUBQUERY

SELECT * FROM EMPLOYEE_SALARY;

SELECT FIRST_NAME,SALARY,
(SELECT AVG(SALARY) FROM EMPLOYEE_SALARY)
FROM EMPLOYEE_SALARY;

SELECT GENDER,MAX(AGE) AS MAXAGE,MIN(AGE) AS MINAGE,AVG(AGE) AS AVG
FROM EMPLOYEE_DEMOGRAPHICS
GROUP BY GENDER;

SELECT AVG(MAXAGE) FROM (SELECT GENDER,MAX(AGE) AS MAXAGE,MIN(AGE) AS MINAGE,AVG(AGE) AS AVG
FROM EMPLOYEE_DEMOGRAPHICS
GROUP BY GENDER) AS AGGREGATOR;