-- temporary table
-- TEMPORARY TABLES WERE ONLY VISIBLE DURING THE SESSING NOT STORED

-- TO STORING THE TEMPORARY RESULTS IN COMPLEX COMMANDS

CREATE TEMPORARY TABLE TEMP_TABLE
( 
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    FAV_MOVIE VARCHAR(50)
);


-- TEMP TABLE LIVES IN MEMORY

-- WE CAN INSET DATA

INSERT INTO TEMP_TABLE VALUES('ALEX','FREMBERS','LEO');

SELECT * FROM TEMP_TABLE;

SELECT * FROM EMPLOYEE_SALARY;

CREATE TEMPORARY TABLE SALARY_OVER_50K
SELECT * FROM EMPLOYEE_SALARY WHERE SALARY>=50000; 

SELECT * FROM SALARY_OVER_50K;

-- ALL TEMP TABLE WILL BE AVAILABLE IN A SESSION AND DO NOT WORK AS SOON AS WE LOGOUT
-- WE USE THE TEMP TABLE WHEN WE WANT TO MAKE THE COMPLEX ANALYSIS
-- CTE'S WERE USED ONLY ONE LEVEL ADVANCEMENT

