-- TRIGGERS AND EVENTS

-- TRIGGERS ARE THE SQL CODES THAT EXECUTE AS SOON AS ANY EVENTS HAPPEN IN SPECIFIC TABLE


-- DATA UPDATED IN EMPLOYEE_SALARY UPDATE IN DATA_DEMOGRAPHICS

SELECT * 
FROM EMPLOYEE_DEMOGRAPHICS;

SELECT *
FROM EMPLOYEE_SALARY;

DELIMITER $$;
	CREATE TRIGGER employee_insert
		AFTER INSERT ON EMLOYEE_SALARY
        FOR EACH ROW
	BEGIN 
		INSERT INTO EMPLOYEE_DEMOFRAPHICS(EMPLOYEE_ID,FIRST_NAME,LAST_NAME)
        VALUES (NEW.EMPLOYEE_ID,NEW.FIRST_NAME,NEW.LAST_NAME);
    END $$
    DELIMITER ;
        
