-- unions
-- ALLOWS TO COMBINE THE DATA ROW WISE

SELECT * FROM EMPLOYEE_DEMOGRAPHICS;

-- JOIN WILL ALLOW US TO COMBINE COLUMN WISE AND 
-- UNION WILL ALLOW US TO COMBINE ROW WISE

SELECT * FROM EMPLOYEE_SALARY;

SELECT * FROM EMPLOYEE_DEMOGRAPHICS
UNION SELECT * FROM EMPLOYEE_SALARY;

-- RANDOM UNION WILL GENERATE A BAD DATA

SELECT FIRST_NAME,LAST_NAME FROM 
employee_demographics
UNION 
SELECT FIRST_NAME,LAST_NAME FROM 
EMPLOYEE_SALARY;

-- IN UNION BY DEFAULT IT IS A DISTINCT FILERED DUPLICATES WERE NOT ALLOWED
SELECT FIRST_NAME,LAST_NAME FROM 
employee_demographics
UNION ALL
SELECT FIRST_NAME,LAST_NAME FROM 
EMPLOYEE_SALARY;
-- UNION ALL WAS USED TO COMBINE ALL DATA IRRESPECTIVE TO THE DATA


SELECT FIRST_NAME,LAST_NAME, 'OLD MAN' AS LABEL 
FROM EMPLOYEE_DEMOGRAPHICS
WHERE AGE>50 AND GENDER='MALE'
UNION 
SELECT FIRST_NAME,LAST_NAME,'OLD WOMAN' AS LABEL
FROM EMPLOYEE_DEMOGRAPHICS
WHERE AGE>40 AND GENDER='FEMALE'
UNION
SELECT FIRST_NAME,LAST_NAME,'HIGHPAID EMPLOYEE' AS LABEL
FROM EMPLOYEE_SALARY
WHERE SALARY>70000;
